@startuml

collections "Producers or Consumers" as PC
participant "Server" as Serv
participant "Message Broker" as MB
participant "Dead Letter Actor" as DLA
participant "Database" as DB

PC -> Serv: Connect
Serv -> PC: Success
PC -> Serv: Message
Serv-> DLA: Incorrect Message
Serv-> PC: Error message
Serv -> MB: Message
MB -> DLA: Incorrect Message
MB-> PC: Error message
DLA -> DB: Persist dead message
DB -> DLA: ok
@enduml