@startuml

collections "Producers" as P
participant "Producer Server" as PServ
participant "Message Broker" as MB
participant "Database" as DB

P -> PServ: Connect
PServ -> P: Success
P -> PServ: Message
PServ -> MB: Message
MB -> DB: Persist message for new consumers
DB -> MB: ok
MB -> P: PUBACK
@enduml