@startuml
[App Supervisor] as AS
[Server Supervisor] as SS
[Producer Server] as PServ
[Consumer Server] as CServ
[Message Broker Supervisor] as MBS
[Message Broker] as MB
[Durable Queue Supervisor] as QS
[Dead Letter Actor] as DLA
[Durable Queue Worker] as DQ1
[Durable Queue Worker] as DQ2
[...] as DQ3
AS --> MBS
AS --> SS
SS --> PServ
SS --> CServ
MBS --> QS
MBS --> MB
MBS --> DLA
QS --> DQ1
QS --> DQ2
QS --> DQ3
@enduml